### ISSUE TITLE
Write CHANGELOG header by default

### ISSUE THREAD

**Issue by estyxx** [autopub/autopub#12]
By mistake, I didn't include the initial header in my CHANGELOG.md 

```
CHANGELOG
=========
```

Autopub is looking for those lines in order to understand where to start writing the RELEASE notes... As it didn't find them continue to overwrite the release lifting only the lasted int he CHANGELOG.md file... 

I think the TODO should be: 

- [x] create CHANGELOG.md file if not found 
- [x] create with the initial header 
- [ ] Mention in the README/docs how to write initial CHANGELOG header [and mention the options `changelog-header` and `changelog-file`]

**Comment by justinmayer** [comment]
Thank you for raising this issue. I had always created the blank `CHANGELOG.md` file manually before, and every time I did it, I mumbled to myself about how janky it felt. So thank you for giving me the nudge I needed to fix it.

[AutoPub 0.1.5](https://github.com/autopub/autopub/releases/tag/0.1.5) is now available, containing what should be an appropriate resolution for this issue: https://github.com/autopub/autopub/commit/29afece085feb2c513572eb3b47c48e9577cd902

Regarding the documentation, I completely agree but am going to defer that for now, mainly because I haven't decided whether to use Sphinx+ReadTheDocs or some other method. But hopefully I will get to that soon.

Let me know how this new release works for you. Thanks again for the collaboration! 💫
