### ISSUE TITLE
Poetry install is failing out of the box

### ISSUE THREAD

**Issue by offbyone** [autopub/autopub#44]
```shellsession
$ poetry install
Configuration file exists at /Users/offbyone/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/offbyone/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Updating dependencies
Resolving dependencies... (4.4s)

Package docutils (0.21.post1) not found.
```

This is remediated by bumping the lower bound python version, since the issue -- which Poetry does _not_ report -- is that Docutils 0.21 needs 3.9+ to work.

**Comment by justinmayer** [comment]
I have fixed that in the past via this method: https://github.com/pelican-plugins/more-categories/commit/427bf5852c4ce68a03d38f684bd2607eb31f44aa

That said, I think Poetry has since been updated to address that problem. I just ran `poetry update && poetry install` via Poetry 1.8.4 and could not reproduce the error you mentioned in the description.

**Comment by offbyone** [comment]
I was definitely running poetry 1.8.4 when I saw this.

**Comment by justinmayer** [comment]
No worries — I think requiring a more recent Python version is a perfectly reasonable thing to do at this point. 👍
