### ISSUE TITLE
Not updating version in pyproject.toml

### ISSUE THREAD

**Issue by estyxx** [autopub/autopub#8]
Hi again! 

I'm trying to run autopub in a Jenkins job, almost everting fine but when it comes the time to upload the library after the poetry build, it seems the version in the file pyproject.toml is still the old one...  

This is the script in the job: 
```
python3.7 -m venv $WORKSPACE/myenv
. $WORKSPACE/myenv/bin/activate

# I know that poetry install will automate this couple of lines, It's just the first try...

pip install -r  $WORKSPACE/mylibrary/requirements.txt
pip install --pre autopub
pip install poetry
pip install githubrelease

cd $WORKSPACE/mylibrary/

# this to be sure that the dist directory is cleaned...
rm -rf $WORKSPACE/mylibrary/dist
export PROJECT_ROOT=$WORKSPACE"/mylibrary"

autopub check
autopub prepare


git remote -v
git push --dry-run
autopub commit																																																		
poetry build
poetry run publish   	
```

this is the output 
```
+ autopub check
+ autopub prepare
+ git push --dry-run
Everything up-to-date
+ autopub commit
###########################
###########################
+ poetry build
Building mylibrary (0.1.1)
 - Building sdist
 - Built mylibrary-0.1.1.tar.gz

 - Building wheel
 - Built mylibrary-0.1.1-py3-none-any.whl
+ poetry run publish
error: mylibrary-0.1.1 already exists! You should use a different version (use --force to override).
Finished: SUCCESS
```

this is my pyproject.toml 
```
[tool.poetry]
name = "mylibrary"
version = "0.1.1"
```

At the end of the building CHANGELOG is updated with the new version (0.1.2) but my pyproject.toml is untouched...

Any ideas why is not updating? Do I have to include other parameters somewhere?? 

Thank you :)

**Comment by justinmayer** [comment]
Hmm. That is quite odd. As you may have seen, the version number in pyproject.toml should be incremented via the `poetry version` invocation, which occurs on this line: https://github.com/autopub/autopub/blob/master/autopub/prepare_release.py#L45

Since the `0.1.2` version was successfully extracted from the output of that command — as shown by the fact that the new version number was added to your changelog — it stands to reason that the `poetry version` command ran successfully. As to why that command did not actually change the contents of pyproject.toml, I honestly cannot say. Have you tried running some of the steps from your script locally? Obviously some of them only make sense in a Jenkins context, but I suggest running as many of them as you can locally to see whether you can replicate this aberrant behavior.

**Comment by estyxx** [comment]
UPDATE 
@justinmayer  I can't comment anymore this issue, there is an error message "You can't comment at this time." ... maybe you should check the repository settings ;)
By the way 

I think that poetry is not updating the version correctly
this [issue](https://github.com/python-poetry/poetry/issues/1696) is still open... 
running locally `poetry version patch` locally doesn't update my pyproject.toml file

**Comment by justinmayer** [comment]
I haven't changed the repository settings, so I don't know why you had trouble commenting. I can only guess it was a temporary GitHub problem. 🤷‍♂ 

If you can't get `poetry version patch` to locally increment the version number in pyproject.toml, then it's not surprising that it doesn't work when the same command is invoked by AutoPub. Do you really only have the above three lines in your pyproject.toml file? If so, that might be the problem. That seems awfully sparse. In which case, perhaps review some of the successfully-working pyproject.toml files that use AutoPub, such as [AutoPub's own](https://github.com/autopub/autopub/blob/master/pyproject.toml).

**Comment by estyxx** [comment]
Ok, poetry was updating this weekend so now the versioning is working :) 
closing this
